-- =========================================================
-- Supabase Database Schema for Multi-User Telegram Sync Hub
-- Timestamps stored in IST (Asia/Kolkata, UTC+5:30)
-- =========================================================

-- Set timezone to IST for this session
SET timezone = 'Asia/Kolkata';

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create User Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    telegram_session_string TEXT,
    telegram_phone TEXT,
    telegram_user_id BIGINT,
    telegram_first_name TEXT,
    telegram_username TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create User Settings Table
CREATE TABLE IF NOT EXISTS public.user_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    webhook_url TEXT DEFAULT '',
    source_channel_id TEXT DEFAULT 'all',
    destination_channel_id TEXT DEFAULT '',
    auto_post_telegram BOOLEAN DEFAULT true,
    auto_post_n8n BOOLEAN DEFAULT true,
    text_prefix TEXT DEFAULT '',
    text_suffix TEXT DEFAULT '',
    find_text TEXT DEFAULT '',
    replace_text TEXT DEFAULT '',
    replacement_rules JSONB DEFAULT '[]'::jsonb,
    override_all_links BOOLEAN DEFAULT false,
    custom_link_url TEXT DEFAULT '',
    remove_all_links BOOLEAN DEFAULT false,
    keyword_filter TEXT DEFAULT '',
    filter_mode TEXT DEFAULT 'all',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Sync Message Logs Table
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    telegram_message_id BIGINT,
    chat_id BIGINT,
    chat_name TEXT,
    raw_message TEXT,
    transformed_message TEXT,
    status TEXT DEFAULT 'pending',
    reason TEXT DEFAULT '',
    webhook_url TEXT DEFAULT '',
    telegram_posted BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast queries on sync_logs by user and date
CREATE INDEX IF NOT EXISTS idx_sync_logs_user_date ON public.sync_logs(user_id, created_at DESC);

-- 5. Row Level Security (RLS) Configuration

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;

-- Profiles RLS Policies
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

-- User Settings RLS Policies
DROP POLICY IF EXISTS "Users can view own settings" ON public.user_settings;
CREATE POLICY "Users can view own settings" ON public.user_settings
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own settings" ON public.user_settings;
CREATE POLICY "Users can update own settings" ON public.user_settings
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own settings" ON public.user_settings;
CREATE POLICY "Users can insert own settings" ON public.user_settings
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Sync Logs RLS Policies
DROP POLICY IF EXISTS "Users can view own sync logs" ON public.sync_logs;
CREATE POLICY "Users can view own sync logs" ON public.sync_logs
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own sync logs" ON public.sync_logs;
CREATE POLICY "Users can insert own sync logs" ON public.sync_logs
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own sync logs" ON public.sync_logs;
CREATE POLICY "Users can delete own sync logs" ON public.sync_logs
    FOR DELETE USING (auth.uid() = user_id);

-- 6. Trigger for Automatic Profile & Settings Initialization on User Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email)
    VALUES (NEW.id, NEW.email)
    ON CONFLICT (id) DO NOTHING;

    INSERT INTO public.user_settings (user_id)
    VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
